### ISSUE TITLE
Does Sleep/Wake work?

### ISSUE THREAD

**Issue by jbwharris** [ibnuh/EFI#1]
I'm building an MSI GL72M 7RDX and have been trying to sort out sleep wake on my machine. I have got it working, but the downside if that I get a flickering screen. Have you solved that issue with your build?

**Comment by ibnuh** [comment]
Unfortunately, I have the same issue, flickering screen after wake up from sleep.

**Comment by jbwharris** [comment]
I was able to fix the flicker. I had to get WhateverGreen working properly and not rely on the older IntelFixUp kexts, but it seems to have improved it. The sleep still isn't perfect, but it is better.
